<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <!-- Отдаём оригинальные ответы Django при ошибках -->
    <httpErrors existingResponse="PassThrough" />

    <!-- Все запросы обрабатываются FastCGI -->
    <handlers>
      <add name="DjangoHandler"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="C:\inetpub\wwwroot\MasterEdApi\ielts-api\venv\Scripts\python.exe|C:\inetpub\wwwroot\MasterEdApi\ielts-api\venv\Lib\site-packages\wfastcgi\wfastcgi.py"
           resourceType="Unspecified"
           requireAccess="Script" />
    </handlers>

    <!-- Параметры FastCGI-приложения -->
    <fastCgi>
      <application fullPath="C:\inetpub\wwwroot\MasterEdApi\ielts-api\venv\Scripts\python.exe"
                   arguments="C:\inetpub\wwwroot\MasterEdApi\ielts-api\venv\Lib\site-packages\wfastcgi\wfastcgi.py">
        <environmentVariables>
          <environmentVariable name="DJANGO_SETTINGS_MODULE" value="ielts_platform.settings" />
          <environmentVariable name="PYTHONPATH" value="C:\inetpub\wwwroot\MasterEdApi\ielts-api" />
        </environmentVariables>
        <!-- логи ошибок Python -->
        <stderrLogEnabled>true</stderrLogEnabled>
        <stderrLogFile>C:\inetpub\wwwroot\MasterEdApi\ielts-api\wfastcgi-stderr.log</stderrLogFile>
      </application>
    </fastCgi>
  </system.webServer>
</configuration>
